dist: xenial   # required for Python >= 3.7
language: python
python:
  - '3.6'

# To install packages which are not on pip
#before_install:
#  - sudo apt-get install ...
#addons:
#  apt:
#    update: true

# blocklist
#branches:
#  except:
#  - branch_name1
#  - branch_name2

# safelist
#branches:
#  only:
#  - branch_name1
#  - branch_name2
