version: '2'
services:
  wam:
    restart: unless-stopped
    image: wam
    container_name: wam
    command: /bin/bash -c "source activate django && cd /code && gunicorn --bind 0.0.0.0:5000 wam.wsgi:application"
    environment:
      WAM_CONFIG_PATH: /config/config.cfg
    ports:
      - "5000:5000"  # Adapt this to your needs!
    volumes:
    - ../config:/config
    networks:
    - wam_network
    depends_on: 
    - wam_db
    - celery
  celery:
    restart: unless-stopped
    build:
      context: ./WAM
      args:
        - WAM_APPS=stemp,stemp_abw,app_mapping  # Activate wam apps here!
    image: wam
    container_name: celery
    command: /bin/bash -c "source activate django && cd /code && celery -A wam -Q wam_queue worker -l info"
    environment:
      WAM_CONFIG_PATH: /config/config.cfg
    volumes:
    - ../config:/config
    networks:
    - wam_network
  wam_db:
    build:
      context: ./WAM/
      dockerfile: Dockerfile.postgis
    image: postgis
    container_name: wam_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wam_database
      POSTGRES_USER: wam_admin
      POSTGRES_PASSWORD: wam_pwd  # Change this!
    volumes:
    - ../django_db:/var/lib/postgresql/data
    networks:
    - wam_network
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: rabbit_vhost    # Change this!
      RABBITMQ_DEFAULT_USER: rabbit_user      # Change this!
      RABBITMQ_DEFAULT_PASS: rabbit_pwd  # Change this!
    networks:
    - wam_network

networks:
  wam_network:
