name: django
dependencies:
- python=3.6
- pip:
  - django
  - gunicorn
  - pandas
  - whitenoise
  - celery
  - configobj
  - django-markdownx
  - django-crispy-forms
  - "git+https://github.com/openego/oedialect"
