# Generated by Django 2.1.3 on 2018-11-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assumption',
            old_name='value_type',
            new_name='unit',
        ),
    ]
